#!/usr/bin/env python3
"""
Understanding Diagram Generator - Anti-Hallucination Visual Verification

Generates Mermaid diagrams that show:
1. Extracted trade flow (HTF -> LTF)
2. Source evidence for each concept (frame + transcript)
3. Confidence indicators for ambiguous concepts
4. Flags concepts that need manual verification

This prevents hallucinated understanding by making extraction TRACEABLE.
Every concept must link to specific evidence.

USAGE:
    python scripts/understanding_diagram_generator.py --video-id 9AL41xON3hA --model-id 5
    python scripts/understanding_diagram_generator.py --from-analysis path/to/analysis.json
    python scripts/understanding_diagram_generator.py --video-id 9AL41xON3hA --save

OUTPUT:
    - Mermaid diagram code
    - Evidence panel (concept -> source mapping)
    - Verification checkpoint summary

DEPENDENCIES:
    - reflective_analyzer.py (accumulated understanding)
    - trade_example_miner.py (trade examples)
"""

import argparse
import json
import sqlite3
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional
from datetime import datetime


# =============================================================================
# Data Structures
# =============================================================================

@dataclass
class ConceptEvidence:
    """Evidence linking a concept to its source."""
    concept_name: str
    concept_type: str  # "BIAS", "POI", "CONFIRMATION", "ENTRY", "STOP", "TARGET"
    frame_reference: Optional[str]  # "frame_008.jpg"
    frame_timestamp: Optional[float]  # seconds
    transcript_quote: Optional[str]  # exact quote from transcript
    visual_observation: Optional[str]  # what's visible in frame
    confidence: float  # 0-1
    source_match: bool  # do transcript and visual agree?
    needs_verification: bool  # confidence < 0.7 or sources don't match
    verification_reason: Optional[str]


@dataclass
class DiagramNode:
    """A node in the trade flow diagram."""
    node_id: str
    label: str
    node_type: str  # "state", "decision", "action", "subgraph_start", "subgraph_end"
    style_class: Optional[str]  # "bullish", "bearish", "waiting", "confirmed"
    timeframe: str  # "DAILY", "H1", "M5", "RISK"


@dataclass
class DiagramEdge:
    """An edge connecting nodes in the diagram."""
    from_node: str
    to_node: str
    label: Optional[str]
    style: Optional[str]  # "dotted", "thick"


@dataclass
class UnderstandingDiagram:
    """Complete understanding diagram with evidence."""
    video_id: str
    model_id: Optional[int]
    model_name: Optional[str]
    generated_at: str

    # Diagram structure
    nodes: list[DiagramNode] = field(default_factory=list)
    edges: list[DiagramEdge] = field(default_factory=list)
    subgraphs: dict = field(default_factory=dict)  # {"DAILY": ["D1", "D2", ...]}

    # Evidence mapping
    evidence: list[ConceptEvidence] = field(default_factory=list)

    # Verification summary
    concepts_total: int = 0
    concepts_verified: int = 0
    concepts_flagged: int = 0

    # Generated content
    mermaid_code: str = ""
    evidence_panel: str = ""
    verification_checkpoint: str = ""


# =============================================================================
# Diagram Templates
# =============================================================================

MERMAID_HEADER = """flowchart TB
    %% Generated by understanding_diagram_generator.py
    %% Video: {video_id}
    %% Model: {model_name}
    %% Generated: {generated_at}

"""

MERMAID_STYLING = """
    %% === STYLING ===
    classDef bullish fill:#90EE90,stroke:#228B22
    classDef bearish fill:#FFB6C1,stroke:#DC143C
    classDef waiting fill:#FFFACD,stroke:#DAA520
    classDef confirmed fill:#87CEEB,stroke:#4169E1
    classDef flagged fill:#FFD700,stroke:#FF8C00,stroke-dasharray: 5 5

"""

EVIDENCE_PANEL_HEADER = """
{separator}
 EVIDENCE MAPPING - {model_name}
{separator}
"""

VERIFICATION_CHECKPOINT_TEMPLATE = """
UNDERSTANDING CHECK - {model_name}

Trade Flow Extracted:
  {flow_summary}

Each concept has source evidence:
{evidence_summary}

{flagged_summary}

Does this understanding match your interpretation of the video? [Y/N]
"""


# =============================================================================
# Understanding Diagram Generator
# =============================================================================

class UnderstandingDiagramGenerator:
    """Generates traceable understanding diagrams from video analysis."""

    def __init__(self, db_path: Optional[Path] = None):
        self.db_path = db_path or Path("data/builder.db")

    def _get_model_info(self, model_id: int) -> dict:
        """Get model information from database."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        cursor.execute("""
            SELECT name, description, model_rules, trade_flow_rules, visual_context_path
            FROM skill_combinations
            WHERE id = ?
        """, (model_id,))

        row = cursor.fetchone()
        conn.close()

        if row:
            return dict(row)
        return {}

    def _get_video_manifest(self, video_id: str) -> dict:
        """Load video manifest with frames and transcript."""
        manifest_path = Path(f"data/video-frames/{video_id}/manifest.json")
        if manifest_path.exists():
            with open(manifest_path) as f:
                return json.load(f)
        return {}

    def _get_trade_examples(self, video_id: str) -> list[dict]:
        """Get trade examples from database."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        cursor.execute("""
            SELECT * FROM trade_examples
            WHERE video_id = ?
        """, (video_id,))

        rows = cursor.fetchall()
        conn.close()

        return [dict(row) for row in rows]

    def _get_visual_evidence(self, model_id: int) -> list[dict]:
        """Get visual evidence from database."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        cursor.execute("""
            SELECT * FROM visual_evidence
            WHERE model_id = ?
        """, (model_id,))

        rows = cursor.fetchall()
        conn.close()

        return [dict(row) for row in rows]

    def _extract_concepts_from_rules(self, model_info: dict) -> list[ConceptEvidence]:
        """Extract concepts from model rules with placeholder evidence."""
        concepts = []

        # Parse model_rules JSON if present
        rules_json = model_info.get("model_rules", "[]")
        try:
            rules = json.loads(rules_json) if rules_json else []
        except json.JSONDecodeError:
            rules = []

        for i, rule in enumerate(rules):
            # Determine concept type from rule text
            rule_lower = rule.lower() if isinstance(rule, str) else ""
            concept_type = "RULE"
            if "bias" in rule_lower or "daily" in rule_lower:
                concept_type = "BIAS"
            elif "fvg" in rule_lower or "poi" in rule_lower or "order block" in rule_lower:
                concept_type = "POI"
            elif "cisd" in rule_lower or "confirm" in rule_lower:
                concept_type = "CONFIRMATION"
            elif "entry" in rule_lower:
                concept_type = "ENTRY"
            elif "stop" in rule_lower:
                concept_type = "STOP"

            concepts.append(ConceptEvidence(
                concept_name=f"Rule {i+1}",
                concept_type=concept_type,
                frame_reference=None,
                frame_timestamp=None,
                transcript_quote=rule if isinstance(rule, str) else str(rule),
                visual_observation=None,
                confidence=0.5,  # Low confidence until verified
                source_match=False,
                needs_verification=True,
                verification_reason="No visual evidence linked"
            ))

        return concepts

    def _build_standard_trading_flow(self) -> tuple[list[DiagramNode], list[DiagramEdge], dict]:
        """Build standard HTF->LTF trading flow structure."""
        nodes = []
        edges = []
        subgraphs = {"DAILY": [], "H1": [], "M5": [], "RISK": []}

        # === DAILY (Bias TF) ===
        daily_nodes = [
            DiagramNode("D1", "Session Open", "state", None, "DAILY"),
            DiagramNode("D2", "PDH or PDL Swept?", "decision", None, "DAILY"),
            DiagramNode("D3", "BULLISH Bias", "state", "bullish", "DAILY"),
            DiagramNode("D4", "BEARISH Bias", "state", "bearish", "DAILY"),
            DiagramNode("D5", "Wait for Sweep", "state", "waiting", "DAILY"),
        ]
        nodes.extend(daily_nodes)
        subgraphs["DAILY"] = ["D1", "D2", "D3", "D4", "D5"]

        edges.extend([
            DiagramEdge("D1", "D2", None, None),
            DiagramEdge("D2", "D3", "PDL Swept + Close > PDL", None),
            DiagramEdge("D2", "D4", "PDH Swept + Close < PDH", None),
            DiagramEdge("D2", "D5", "No Sweep", None),
            DiagramEdge("D5", "D2", None, "dotted"),
        ])

        # === H1 (Confirmation TF) ===
        h1_nodes = [
            DiagramNode("H1A", "POI Detected?", "decision", None, "H1"),
            DiagramNode("H1B", "POI Zone Set", "state", None, "H1"),
            DiagramNode("H1C", "Scan for POI", "state", "waiting", "H1"),
            DiagramNode("H1D", "Price in Reaction Zone?", "decision", None, "H1"),
            DiagramNode("H1E", "Count C2/C3 Candles", "state", None, "H1"),
            DiagramNode("H1F", "Wait for Touch", "state", "waiting", "H1"),
            DiagramNode("H1G", "MinConfirmation Met?", "decision", None, "H1"),
            DiagramNode("H1H", "H1 CONFIRMED", "state", "confirmed", "H1"),
        ]
        nodes.extend(h1_nodes)
        subgraphs["H1"] = ["H1A", "H1B", "H1C", "H1D", "H1E", "H1F", "H1G", "H1H"]

        edges.extend([
            DiagramEdge("H1A", "H1B", "FVG/OB Found", None),
            DiagramEdge("H1A", "H1C", "None", None),
            DiagramEdge("H1C", "H1A", None, "dotted"),
            DiagramEdge("H1B", "H1D", None, None),
            DiagramEdge("H1D", "H1E", "Yes", None),
            DiagramEdge("H1D", "H1F", "No", None),
            DiagramEdge("H1F", "H1D", None, "dotted"),
            DiagramEdge("H1E", "H1G", None, None),
            DiagramEdge("H1G", "H1H", "C2/C3 Complete", None),
            DiagramEdge("H1G", "H1E", "Counting...", "dotted"),
        ])

        # === M5 (Entry TF) ===
        m5_nodes = [
            DiagramNode("M1", "CISD Pattern?", "decision", None, "M5"),
            DiagramNode("M2", "Track Series", "state", None, "M5"),
            DiagramNode("M3", "Wait for CISD", "state", "waiting", "M5"),
            DiagramNode("M4", "Close Through Series?", "decision", None, "M5"),
            DiagramNode("M5A", "OB Formed", "state", None, "M5"),
            DiagramNode("M6", "Stop <= MaxTicks?", "decision", None, "M5"),
            DiagramNode("M7", "EXECUTE ENTRY", "action", "confirmed", "M5"),
            DiagramNode("M8", "Skip - Stop Wide", "state", "flagged", "M5"),
        ]
        nodes.extend(m5_nodes)
        subgraphs["M5"] = ["M1", "M2", "M3", "M4", "M5A", "M6", "M7", "M8"]

        edges.extend([
            DiagramEdge("M1", "M2", "Opposing Series Started", None),
            DiagramEdge("M1", "M3", "No", None),
            DiagramEdge("M3", "M1", None, "dotted"),
            DiagramEdge("M2", "M4", None, None),
            DiagramEdge("M4", "M5A", "Yes", None),
            DiagramEdge("M4", "M2", "No", "dotted"),
            DiagramEdge("M5A", "M6", None, None),
            DiagramEdge("M6", "M7", "Yes", None),
            DiagramEdge("M6", "M8", "No", None),
        ])

        # === RISK MANAGEMENT ===
        risk_nodes = [
            DiagramNode("R1", "Entry Filled", "state", None, "RISK"),
            DiagramNode("R2", "Set Stop & Target", "action", None, "RISK"),
            DiagramNode("R3", "Profit >= 1R?", "decision", None, "RISK"),
            DiagramNode("R4", "Move to Breakeven", "action", None, "RISK"),
            DiagramNode("R5", "Monitor", "state", None, "RISK"),
            DiagramNode("R6", "Exit Condition?", "decision", None, "RISK"),
            DiagramNode("R7", "Exit Profit", "state", "bullish", "RISK"),
            DiagramNode("R8", "Exit Loss", "state", "bearish", "RISK"),
        ]
        nodes.extend(risk_nodes)
        subgraphs["RISK"] = ["R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8"]

        edges.extend([
            DiagramEdge("R1", "R2", None, None),
            DiagramEdge("R2", "R3", None, None),
            DiagramEdge("R3", "R4", "Yes", None),
            DiagramEdge("R3", "R5", "No", None),
            DiagramEdge("R5", "R3", None, "dotted"),
            DiagramEdge("R4", "R6", None, None),
            DiagramEdge("R6", "R7", "Hit Target", None),
            DiagramEdge("R6", "R8", "Hit Stop", None),
        ])

        # Cross-timeframe connections
        edges.extend([
            DiagramEdge("D3", "H1A", None, None),
            DiagramEdge("D4", "H1A", None, None),
            DiagramEdge("H1H", "M1", None, None),
            DiagramEdge("M7", "R1", None, None),
        ])

        return nodes, edges, subgraphs

    def _generate_mermaid_code(self, diagram: UnderstandingDiagram) -> str:
        """Generate Mermaid diagram code."""
        lines = []

        # Header
        lines.append(MERMAID_HEADER.format(
            video_id=diagram.video_id,
            model_name=diagram.model_name or "Unknown Model",
            generated_at=diagram.generated_at
        ))

        # Subgraphs
        tf_labels = {
            "DAILY": "DAILY - Bias Detection",
            "H1": "H1 - POI & Confirmation",
            "M5": "M5 - Entry Execution",
            "RISK": "Position Management"
        }
        tf_icons = {
            "DAILY": "",
            "H1": "",
            "M5": "",
            "RISK": ""
        }

        for tf, node_ids in diagram.subgraphs.items():
            label = tf_labels.get(tf, tf)
            lines.append(f'    subgraph {tf}["{label}"]')
            lines.append('        direction TB')

            for node in diagram.nodes:
                if node.node_id in node_ids:
                    if node.node_type == "decision":
                        lines.append(f'        {node.node_id}{{{node.label}}}')
                    elif node.node_type == "action":
                        lines.append(f'        {node.node_id}[{node.label}]')
                    else:
                        lines.append(f'        {node.node_id}[{node.label}]')

            lines.append('    end')
            lines.append('')

        # Edges
        lines.append('    %% === CONNECTIONS ===')
        for edge in diagram.edges:
            arrow = "-->"
            if edge.style == "dotted":
                arrow = "-.->"

            if edge.label:
                lines.append(f'    {edge.from_node} {arrow}|{edge.label}| {edge.to_node}')
            else:
                lines.append(f'    {edge.from_node} {arrow} {edge.to_node}')

        # Styling
        lines.append(MERMAID_STYLING)

        # Apply classes
        bullish = [n.node_id for n in diagram.nodes if n.style_class == "bullish"]
        bearish = [n.node_id for n in diagram.nodes if n.style_class == "bearish"]
        waiting = [n.node_id for n in diagram.nodes if n.style_class == "waiting"]
        confirmed = [n.node_id for n in diagram.nodes if n.style_class == "confirmed"]
        flagged = [n.node_id for n in diagram.nodes if n.style_class == "flagged"]

        if bullish:
            lines.append(f'    class {",".join(bullish)} bullish')
        if bearish:
            lines.append(f'    class {",".join(bearish)} bearish')
        if waiting:
            lines.append(f'    class {",".join(waiting)} waiting')
        if confirmed:
            lines.append(f'    class {",".join(confirmed)} confirmed')
        if flagged:
            lines.append(f'    class {",".join(flagged)} flagged')

        return '\n'.join(lines)

    def _generate_evidence_panel(self, diagram: UnderstandingDiagram) -> str:
        """Generate evidence panel showing concept-source mapping."""
        separator = "=" * 65
        lines = []

        lines.append(EVIDENCE_PANEL_HEADER.format(
            separator=separator,
            model_name=diagram.model_name or "Unknown Model"
        ))

        # Group evidence by type
        by_type = {}
        for ev in diagram.evidence:
            if ev.concept_type not in by_type:
                by_type[ev.concept_type] = []
            by_type[ev.concept_type].append(ev)

        type_order = ["BIAS", "POI", "CONFIRMATION", "ENTRY", "STOP", "TARGET", "RULE"]

        for concept_type in type_order:
            if concept_type not in by_type:
                continue

            lines.append(f" {concept_type}")
            lines.append("-" * 65)

            for ev in by_type[concept_type]:
                status = "X" if ev.needs_verification else "V"
                frame_info = f"frame: {ev.frame_reference}" if ev.frame_reference else "no frame"
                timestamp_info = f"@ {ev.frame_timestamp:.0f}s" if ev.frame_timestamp else ""

                lines.append(f"   [{status}] {ev.concept_name}")
                if ev.frame_reference:
                    lines.append(f"       Frame: {ev.frame_reference} {timestamp_info}")
                if ev.transcript_quote:
                    quote = ev.transcript_quote[:60] + "..." if len(ev.transcript_quote) > 60 else ev.transcript_quote
                    lines.append(f'       Transcript: "{quote}"')
                if ev.visual_observation:
                    lines.append(f"       Visual: {ev.visual_observation}")
                if ev.needs_verification:
                    lines.append(f"       !! NEEDS VERIFICATION: {ev.verification_reason}")
                lines.append("")

        lines.append(separator)
        return '\n'.join(lines)

    def _generate_verification_checkpoint(self, diagram: UnderstandingDiagram) -> str:
        """Generate verification checkpoint for user approval."""
        # Build flow summary
        flow_steps = ["Daily Bias", "POI Detection", "H1 Confirmation", "M5 CISD", "Entry"]
        flow_summary = " -> ".join(f"[{i+1}] {step}" for i, step in enumerate(flow_steps))

        # Build evidence summary
        evidence_lines = []
        for ev in diagram.evidence:
            status = "V" if not ev.needs_verification else "!"
            source = ev.frame_reference or "transcript"
            if ev.transcript_quote:
                quote = ev.transcript_quote[:40] + "..." if len(ev.transcript_quote) > 40 else ev.transcript_quote
                evidence_lines.append(f"  {status} {ev.concept_name}: {source} - \"{quote}\"")
            else:
                evidence_lines.append(f"  {status} {ev.concept_name}: {source}")

        evidence_summary = '\n'.join(evidence_lines)

        # Flagged summary
        flagged = [ev for ev in diagram.evidence if ev.needs_verification]
        if flagged:
            flagged_lines = ["\n!! REQUIRES MANUAL VERIFICATION:"]
            for ev in flagged:
                flagged_lines.append(f"   - {ev.concept_name}: {ev.verification_reason}")
            flagged_summary = '\n'.join(flagged_lines)
        else:
            flagged_summary = "\nAll concepts have high-confidence evidence."

        return VERIFICATION_CHECKPOINT_TEMPLATE.format(
            model_name=diagram.model_name or "Unknown Model",
            flow_summary=flow_summary,
            evidence_summary=evidence_summary,
            flagged_summary=flagged_summary
        )

    def generate(
        self,
        video_id: str,
        model_id: Optional[int] = None,
        analysis_path: Optional[Path] = None
    ) -> UnderstandingDiagram:
        """Generate complete understanding diagram."""

        # Get model info
        model_info = {}
        model_name = "Unknown Model"
        if model_id:
            model_info = self._get_model_info(model_id)
            model_name = model_info.get("name", f"Model {model_id}")

        # Build standard flow
        nodes, edges, subgraphs = self._build_standard_trading_flow()

        # Extract concepts from model rules
        concepts = self._extract_concepts_from_rules(model_info)

        # Enrich with trade examples if available
        trade_examples = self._get_trade_examples(video_id)
        if trade_examples:
            # Add stop reference evidence
            stop_refs = [t.get("stop_reference_point") for t in trade_examples if t.get("stop_reference_point")]
            if stop_refs:
                from collections import Counter
                dominant = Counter(stop_refs).most_common(1)[0]
                concepts.append(ConceptEvidence(
                    concept_name="Stop Reference",
                    concept_type="STOP",
                    frame_reference=trade_examples[0].get("frame_path", "").split("/")[-1] if trade_examples else None,
                    frame_timestamp=trade_examples[0].get("timestamp_seconds"),
                    transcript_quote=None,
                    visual_observation=f"Stop at {dominant[0]} ({dominant[1]} examples)",
                    confidence=dominant[1] / len(stop_refs) if stop_refs else 0,
                    source_match=True,
                    needs_verification=dominant[1] / len(stop_refs) < 0.7 if stop_refs else True,
                    verification_reason="Low consistency" if dominant[1] / len(stop_refs) < 0.7 else None
                ))

        # Count stats
        verified = len([c for c in concepts if not c.needs_verification])
        flagged = len([c for c in concepts if c.needs_verification])

        diagram = UnderstandingDiagram(
            video_id=video_id,
            model_id=model_id,
            model_name=model_name,
            generated_at=datetime.now().isoformat(),
            nodes=nodes,
            edges=edges,
            subgraphs=subgraphs,
            evidence=concepts,
            concepts_total=len(concepts),
            concepts_verified=verified,
            concepts_flagged=flagged
        )

        # Generate outputs
        diagram.mermaid_code = self._generate_mermaid_code(diagram)
        diagram.evidence_panel = self._generate_evidence_panel(diagram)
        diagram.verification_checkpoint = self._generate_verification_checkpoint(diagram)

        return diagram

    def save_diagram(self, diagram: UnderstandingDiagram) -> int:
        """Save diagram to database."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute("""
            INSERT INTO understanding_diagrams (
                model_id, video_id, mermaid_code, evidence_panel,
                concepts_extracted, concepts_verified, concepts_flagged
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            diagram.model_id,
            diagram.video_id,
            diagram.mermaid_code,
            diagram.evidence_panel,
            diagram.concepts_total,
            diagram.concepts_verified,
            diagram.concepts_flagged
        ))

        diagram_id = cursor.lastrowid
        conn.commit()
        conn.close()

        return diagram_id


# =============================================================================
# CLI Entry Point
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Generate understanding diagrams with evidence traceability"
    )
    parser.add_argument(
        "--video-id",
        type=str,
        required=True,
        help="Video ID to generate diagram for"
    )
    parser.add_argument(
        "--model-id",
        type=int,
        help="Model ID to use for context"
    )
    parser.add_argument(
        "--from-analysis",
        type=Path,
        help="Load analysis from JSON file"
    )
    parser.add_argument(
        "--save",
        action="store_true",
        help="Save diagram to database"
    )
    parser.add_argument(
        "--output-mermaid",
        type=Path,
        help="Output Mermaid diagram to file"
    )
    parser.add_argument(
        "--output-evidence",
        type=Path,
        help="Output evidence panel to file"
    )
    parser.add_argument(
        "--output-checkpoint",
        type=Path,
        help="Output verification checkpoint to file"
    )

    args = parser.parse_args()

    generator = UnderstandingDiagramGenerator()

    diagram = generator.generate(
        video_id=args.video_id,
        model_id=args.model_id,
        analysis_path=args.from_analysis
    )

    # Output Mermaid diagram
    print("\n" + "=" * 70)
    print("MERMAID DIAGRAM")
    print("=" * 70)
    print(diagram.mermaid_code)

    if args.output_mermaid:
        with open(args.output_mermaid, "w") as f:
            f.write(diagram.mermaid_code)
        print(f"\nMermaid saved to: {args.output_mermaid}")

    # Output evidence panel
    print("\n" + diagram.evidence_panel)

    if args.output_evidence:
        with open(args.output_evidence, "w") as f:
            f.write(diagram.evidence_panel)

    # Output verification checkpoint
    print("\n" + "=" * 70)
    print(diagram.verification_checkpoint)
    print("=" * 70)

    if args.output_checkpoint:
        with open(args.output_checkpoint, "w") as f:
            f.write(diagram.verification_checkpoint)

    # Summary
    print(f"\nSummary:")
    print(f"  Total concepts: {diagram.concepts_total}")
    print(f"  Verified:       {diagram.concepts_verified}")
    print(f"  Need review:    {diagram.concepts_flagged}")

    if args.save:
        diagram_id = generator.save_diagram(diagram)
        print(f"\nSaved to database with ID: {diagram_id}")


if __name__ == "__main__":
    main()
